services:
  - type: web
    name: nqnghia-tools
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    envVars:
      - key: RENDER
        value: true
